### ISSUE TITLE
feat: Implement Semaphore Groups contract

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/semaphore-stellar-contracts#1]
Migrate the Semaphore Groups contract to Soroban.

Resource: https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/SemaphoreGroups.sol
https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/interfaces/ISemaphoreGroups.sol

**Comment by mubarak23** [comment]
i will study the code and migrate to

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged

software engineering background, backend & smart contract dev looking to make first contribution on this project

How I plan on tackling this issue
Perform the necessary migrations and be sure to work on feedback & recommendations. Can deliver with a day upon assignment

**Comment by ChrisFernandezVivas** [comment]
hi , im from dojo coding, I can take this issue, is only convert to soroban env :) for be honest I don't know about soroban coding languages but I can learn about that

**Comment by Gerson2102** [comment]
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Rust projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by josephpdf** [comment]
Hi!, my name is Joseph Poveda.
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3.
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
To migrate the Semaphore Groups contract to Soroban, follow these steps:

Analyze the Original Contract: Review the functionalities in SemaphoreGroups.sol and ISemaphoreGroups.sol from the provided links, understanding group management, permissions, and events in Ethereum.

Get Familiar with Soroban: Learn Soroban's SDK and libraries, as its syntax and features may differ from Ethereum.

Port the Code: Adapt the group creation and management functionalities to Soroban, keeping its unique structure in mind.

Testing: Develop unit tests in Soroban to ensure the migrated contract works as expected.

**Comment by martinvibes** [comment]
I'd like to take this issue.

### 1. Key Components:

- Base Contract: SemaphoreGroups.sol
- Interface: ISemaphoreGroups.sol

### 1. Main Functions to Migrate:

- Create groups
- Update group parameters
- Group member management (add/remove)
- Group verification logic

### 3. Technical Requirements:

- Convert Solidity code to Rust
- Implement Soroban contract interface
- Maintain group trees functionality
- Keep zero-knowledge proof verification

**Comment by KoxyG** [comment]
Hi @bitfalt @evgongora,

I’m applying for this issue via the [OnlyDust platform](https://app.onlydust.com/p/semaphore-stellar).

### Background and Relevant Experience

My name is Koxy, a blockchain Rust developer and [Stellar ecosystem contributor](https://github.com/stellar/stellar-docs/pull/902). I’m the creator of the YouTube series [Let’s Get Soroban](https://www.youtube.com/@Koxy_Dev), where I delve into hands-on development with Rust and the Stellar platform.

With a strong background in open-source development and a deep familiarity with Stellar’s architecture, I’m well-positioned to undertake the migration of the Semaphore Groups contract to Soroban.

I’m excited to implement immediate solutions and collaborate with the team on long-term improvements to enhance the Semaphore protocol.

### Approach to Tackling This Issue

To address this migration, I plan to:

1. **Implement a Trait for SemaphoreGroups**: Develop a trait and implement it to create a compatible contract for the Soroban platform.

2. **Thorough Testing**: Write comprehensive tests that cover a wide range of scenarios, including edge cases. As i proposed [here](https://github.com/ZencypherSolutions/semaphore-stellar-contracts/issues/3#issuecomment-2448270617).

3. **Update Documentation**: Revise CLI documentation and help messages to reflect the changes accurately.

4. **Submit PR**: Create a detailed pull request with explanations of the changes and their rationale.

5. **Collaborate and Iterate**: Work closely with maintainers to incorporate feedback and refine the solution as necessary.

This is a sample contract written in [soroban](https://github.com/KoxyG/VotingContractStellar).

---

Thank you for your consideration. Looking forward to contributing!

**Comment by KoxyG** [comment]
Hi @bitfalt I can see this issue is still open. Once again, i am requesting to be assigned to this. I have experience in writing soroban smart contracts and i know i can handle this very well.

**Comment by evgongora** [comment]
Hello @KoxyG! Go ahead, let me know if you have any questions.

**Comment by KoxyG** [comment]
> Hello @KoxyG! Go ahead, let me know if you have any questions.

Nice. Thanks. No problem

**Comment by KoxyG** [comment]
Hi @bitfalt i am done with my contract https://github.com/ZencypherSolutions/semaphore-stellar-contracts/pull/14
