### ISSUE TITLE
[Semaphore Integration] Issue 5: Implement Protocol 22 to Semaphore Groups contract

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-contracts#15]
This contract manages the group (e.g., a Merkle tree of user commitments) and handles:

bls12_381_hash_to_g1:
Hash user commitments (e.g., public keys or identity credentials) to curve points when adding them to the Merkle tree.
Use this to compute hashed inputs for verification.

References
https://github.com/worldcoin/semaphore-rs/tree/main/crates/trees/src/imt
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0059.md

**Comment by JoE11-y** [comment]
Can I try solving this issue?

**Comment by KoxyG** [comment]
Hi @evgongora,
Stellar has recently released the Protocol 22 upgrade. With this update, I can conduct thorough research and ensure its seamless implementation into the existing contract.

**Comment by kien6034** [comment]
I have strong experience with rust, and have been learning and researching about cryptography for about 4 months (ecdsa, schnorr, frost,...). I’d like to resolve this.

**Comment by TropicalDog17** [comment]
Hi, I have experience in various open source Rust projects.

carbonable-labs/svgenerator#10

https://github.com/paradigmxyz/reth/commits/main/?author=TropicalDog17

https://github.com/foundry-rs/foundry/commits/master/?author=TropicalDog17

I will first review the Incremental Merkle Tree concepts, then I will take some time to learn about the Semaphore protocols, and I will try to draft a PR as soon as possible for reviewer/maintainer to know my progress. I will also try to communicate with reviewer/maintainer to get the needed feedback and to improve on my pull request.
