### ISSUE TITLE
docs: edit README file

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-contracts#4]
Edit README file for the repo explaining that all the technical documentation and research would be in this repository. Research files must be added under the research folder.

Also mention that for further assistance they can join the following Telegram groups:
Semaphore-Stellar (maintainers of Semaphore Stellar): https://t.me/+-9623JNgGjEyNzI5
Semaphore Community (core developers of the Semaphore protocol): @semaphore_community (search it on Telegram

**Comment by Jemiiah** [comment]
@evgongora I'm an active contributor to documentation issues during OD Hack pls I would love to work on this issue

**Comment by 0xBinayak** [comment]
@evgongora I am a  new contributer and have contributed to may repos i think i can make a  README file for the repo with  very easy and clear instructions.
 Time frame :under 1 Day

**Comment by Benjtalkshow** [comment]
Hello @evgongora 
I can get this task done in 5hrs max.

**Comment by KevinLatino** [comment]
I am a Dojo Coding Member

I would like to take on the task of editing the README.md file for the repository. Here’s my plan for the updates:

Overview of the Repository:

Clearly state that all technical documentation and research files will be included in this repository.
Emphasize the importance of organizing files appropriately, specifically mentioning that research files should be added under the "research" folder.
Assistance Resources:

Include a section that directs users to join the following Telegram groups for further assistance:
Semaphore-Stellar (maintainers of Semaphore Stellar): Join here
Semaphore Community (core developers of the Semaphore protocol): @semaphore_community (search for it on Telegram)
Encouragement for Contributions:

Invite contributors to share their work and engage with the community.
I look forward to making these updates and welcome any additional suggestions or requirements you may have!

**Comment by JosueBrenes** [comment]
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

**How I would resolve this**

To resolve this request, I would update the README file as follows:

1. **Include details on technical documentation and research**  
   State that all technical documentation and research files will be located in this repository. Instruct that all research files must be added under the `research` folder.

2. **Add additional support links**  
   Mention in the README that, for further assistance, users can join the following Telegram groups:

   - **Semaphore-Stellar** (maintainers of Semaphore Stellar): [https://t.me/+-9623JNgGjEyNzI5](https://t.me/+-9623JNgGjEyNzI5)
   - **Semaphore Community** (core developers of the Semaphore protocol): `@semaphore_community` (search on Telegram).

**Comment by PoulavBhowmick03** [comment]
Would love to tackle this!

I will update the `README.md` to clarify that this repository contains all technical documentation and research materials. I'll add a note instructing contributors to place any research files in the designated `research` folder.

Additionally, I’ll include links for further assistance, directing users to the relevant Telegram groups:
1. Semaphore-Stellar 
(https://t.me/+-9623JNgGjEyNzI5)
2. Semaphore Community (core developers of the Semaphore protocol) 

This update will ensure clear guidelines and helpful resources are readily available to everyone.

**Comment by josephpdf** [comment]
Hi!, my name is Joseph Poveda.
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3.
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
To approach this issue, I would edit the README to clarify that all technical documentation and research will reside in this repository, with research files specifically located in the research folder. Additionally, I’d add information for contributors seeking support, guiding them to join the relevant Telegram groups, including Semaphore-Stellar for maintainer support and Semaphore Community for core developer interaction, with the provided links for direct access.

**Comment by NueloSE** [comment]
Could I grab this task?

**Comment by petersdt** [comment]
Could I take a shot at this?

**Comment by martinvibes** [comment]
I’d like to work on this.
kindly assign ;)

## Update the README.md to:

- Explain that the repository contains all technical documentation and research files.
- Clarify that research files should be added under the research folder.
- Include links to Telegram groups for additional assistance:
- Semaphore-Stellar: [Telegram link](https://t.me/+-9623JNgGjEyNzI5) (maintainers)
- Semaphore Community: Search "@semaphore_community" on Telegram (core developers).

#### i would make sure it is very well self explained even to begginners

**Comment by derianrddev** [comment]
Hello, I’m Derian, a software engineer focused on full-stack web development and currently part of Dojo Coding. I’d like to work on this issue.

How I would resolve the issue:

Edit the README.md file with the sections described in the issue. 
Save and upload the file to the repository.
If I have questions, I’ll ask them as soon as possible in the Telegram group. 
I will open a PR and wait for your feedback. 
Make any necessary changes according to the PR review.

**Comment by KoxyG** [comment]
Hi @bitfalt and @evgongora, 👋

I’m applying for this issue through the [OnlyDust platform](https://app.onlydust.com/p/semaphore-stellar-contracts).

I'd like to work on updating the README for this repository to align with the new structure and emphasize the inclusion of technical documentation and research materials. As a [Stellar ecosystem contributor](https://github.com/stellar/stellar-docs/pull/902), I’m familiar with the importance of well-structured documentation and am excited to support this project.

### Proposed README Updates

The README will:

1. **Overview of Purpose**: Provide a clear purpose statement, outlining the goal of this repository as a central hub for both development and research related to the Semaphore Groups contract on Soroban.
  
2. **Research and Technical Documentation Section**: Highlight the "research" folder for all technical and research files, including methodology, findings, and ongoing documentation, ensuring contributors and users can easily locate in-depth information.

3. **Contributor Guidance**: Include a "Getting Started" section to guide new contributors on where to find relevant files and how to begin working on tasks.

4. **Project Structure and Progress**: Outline the folder structure, such as contracts, tests, and research, and update on the migration progress.

5. **Link to Relevant Issues**: Add links to ongoing issues and the OnlyDust platform for context.

Thank you for considering my proposal! Let me know if there are additional areas you’d like covered.

**Comment by jsandinoDev** [comment]
Hi @bitfalt  I'm a full-stack developer with web3 experience member of Dojo Coding, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems. I have worked on modifying the readme in projects like Shinigami & GoStarkme
I would love to work on this issue

**Comment by anonfedora** [comment]
A fullstack Blockchain developer.
    First time documentation contributor:

Will ensure comprehensive explanation of technical documentation and research and making sure research files are in the appropriate location (research folder).

Also, make sure URL for further assistance (to telegram channel) is updated.
