### ISSUE TITLE
docs: add PR template

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-contracts#6]
The doc must have:
Summary, Changes Made, Related Issues, Checklist with brief description on each one or bullet points.

Example:

![image](https://github.com/user-attachments/assets/d06fbe85-961e-434a-96fa-37952b544182)

**Comment by sanieni6** [comment]
I'd love to work on this! I am a front end dev, i am familiar with ci workflows, please allow me to work on tnis.

**Comment by diegoTech14** [comment]
Hello, I'm Diego a software engineer from Costa Rica and  member of Dojo Coding ⛩️ I've created some documentation for projects like KaizenNodeLabs, ByteBeasts and Dipdup, I would love to contribute to this issue

You can see my OnlyDust profile **[here](https://app.onlydust.com/u/diegoTech14)**

**Comment by NueloSE** [comment]
Can I work on this, please?

**Comment by t0fudev** [comment]
Hi, I'm currently a software enginner student. I am confident of completing this task successfully.

I would do the following to solve the task:

- Create a new folder named '.github' and then in this folder I would create a new folder named 'PR_Template'.
-  Then add a new file named 'pr_template.md'.
- Write the template content given (Summary, Changes made, Related Issues, etc).
- Test the template and fix it if there are any suggestions.

**Comment by JosueBrenes** [comment]
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take **1 day** to complete.

## Solution Plan

### Step 1: Document Structure
I'll start by creating a structured document that includes sections for **Summary**, **Changes Made**, **Related Issues**, **Other Information**, and **Checklist**.

### Step 2: Detailed Sections
- **Summary**: I'll provide a concise explanation of the purpose of the changes.
- **Changes Made**: I will list specific updates or modifications in bullet points.
- **Related Issues**: I'll link the relevant issue numbers or titles to provide context.
- **Other Information**: I'll add any additional context or dependencies that are relevant.
- **Checklist**: I'll implement a checklist with tasks like adhering to style guidelines, performing a self-review, and running tests.

### Step 3: Markdown Format
I'll format each section in GitHub Markdown to ensure clarity and easy reading. This includes adding checkboxes for each item in the checklist.

### Step 4: Save as Template
Finally, I'll save the document as a reusable template to maintain consistency across future issues.

### Expected Outcome
A structured, reusable template for documenting issue resolutions, with a clear checklist and all necessary information for reviewers.

---
